### ISSUE TITLE
Download button does nothing.

### ISSUE THREAD

**Issue by ahinojos0029** [Blobby-Boi/Blobwifi#2]
I have copy+pasted the whole thing, yet somehow the Download button seems to be doing absolutely nothing. Dunno if its on my end but thats what's happening.

**Comment by 25HoursaDay** [comment]
same

**Comment by Person-Who-Exists** [comment]
Upon opening the site, it generates a `"<a class='gotoLine' href='#200:31'>200:31</a> Uncaught SyntaxError: Unexpected number"` error

When pressing the button, it generates a `"<a class='gotoLine' href='#162:31'>162:31</a> Uncaught ReferenceError: gen is not defined"` error

Edit: At least in jsfiddle
Edit: Tried moving js to <head> so it would load before the html, didn't work

**Comment by ABadGame** [comment]
> Upon opening the site, it generates a `"<a class='gotoLine' href='#200:31'>200:31</a> Uncaught SyntaxError: Unexpected number"` error
> 
> When pressing the button, it generates a `"<a class='gotoLine' href='#162:31'>162:31</a> Uncaught ReferenceError: gen is not defined"` error
> 
> Edit: At least in jsfiddle

So it doesnt even work then.

**Comment by raninderr** [comment]
Bruh how am I supposed  to unblock stuff >:(

**Comment by Blobby-Boi** [comment]
I have fixed this. The issue came from a little typo when setting the DNS servers. (I added a new system where you no longer need to set the DNS servers to the google ones, it just does it for you)

If you still encounter this issue, please let me know!
