### ISSUE TITLE
Repo Source

### ISSUE THREAD

**Issue by killsecurly** [Blobby-Boi/Blobwifi#7]
This repo seems to be a fork of SecurlyONC and cauDNS, with support of omadaDNS, caub, dragon73101, and killsecurly.

If so, would you be able to add credits?

**Comment by Blobby-Boi** [comment]
I did not use any of those actually. Its a modified version of regular CAUB that uses google name servers back before I even knew that cauDNS and omadaDNS existed. If you want, I can give credit anyway though.

**Comment by killsecurly** [comment]
OK, thanks for responding. Of course, Securly's Filter system would be sufficient with Caub, but Classroom may not work.

Resolving issue, as completed.
